### PR TITLE
MCKIN-23104 Integrate EOC journal platform translations for chinese

### PR DESCRIPTION
**Pull request by wasifarbisoft**
The Chinese translation folder was wrongly named which was causing translation to fail for Chinese language.

### CODE REVIEW

**Comment by wasifarbisoft** [comment]
@xitij2000 , Please review this pull request.

**Review by viadanna — APPROVED** [review]
Good to go 👍

- [x] I read through the code.

**Comment by wasifarbisoft** [comment]
@viadanna Can you please create the release for this as well? i.e 0.9.1

**Comment by viadanna** [comment]
Done @wasifarbisoft

**Pull request merged**
